export const COLUMNS_DATA = [
	{ id: 1, name: 'date', label: '출고요청일자', minWidth: 110 },
	{ id: 2, name: 'release_status', label: '출고 상태', minWidth: 110 },
	{ id: 3, name: 'release_type', label: '출고 유형', minWidth: 110 },
	{ id: 4, name: 'file_name', label: '출고서파일명', minWidth: 110, align: 'center' },
	{ id: 5, name: 'id', label: '액셀 행 순번', minWidth: 110, align: 'center' },
	{ id: 6, name: 'map_status', label: '매핑상태', minWidth: 110, align: 'center' },
	{ id: 7, name: 'order_form', label: '주문서 양식', minWidth: 110, align: 'center' },
	{ id: 8, name: 'order_num', label: '주문번호', minWidth: 110, align: 'center' },
	{ id: 9, name: 'linked_product', label: '연동상품ID', minWidth: 110, align: 'center' },
	{ id: 10, name: 'product_name', label: '주문명', minWidth: 110, align: 'center' },
	{ id: 11, name: 'comp_product_name', label: '콜로상품명', minWidth: 110, align: 'center' },
	{ id: 12, name: 'comp_product_code', label: '콜로상품코드', minWidth: 110, align: 'center' },
	{ id: 13, name: 'comp_product_id', label: '콜로상품ID', minWidth: 110, align: 'center' },
	{ id: 14, name: 'amount', label: '주문수량', minWidth: 110, align: 'center' },
	{ id: 15, name: 'unit', label: '주문단위', minWidth: 110, align: 'center' },
	{ id: 16, name: 'release_amount', label: '출고수량', minWidth: 110, align: 'center' },
	{ id: 17, name: 'warehouse', label: '출고창고명', minWidth: 110, align: 'center' },
	{ id: 18, name: 'lack_stock', label: '재고부족여부', minWidth: 110, align: 'center' },
	{ id: 19, name: 'warehouse', label: '주문자', minWidth: 110, align: 'center' },
	{ id: 20, name: 'user_phone', label: '전화번호', minWidth: 110, align: 'center' },
];
